// <auto-generated />
using System;
using Blocwerk.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blocwerk.Core.Migrations
{
    [DbContext(typeof(BlocwerkDbContext))]
    partial class BlocwerkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blocwerk.Core.Entities.ActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BoulderId", "Timestamp");

                    b.HasIndex("WallId", "Timestamp");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoulderId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Boulder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FootColorOnly")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("HandsFollowFeet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHistoric")
                        .HasColumnType("boolean");

                    b.Property<bool>("KickboardFootholdsOn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WallId");

                    b.ToTable("Boulders");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoulderId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("BoulderComments");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderFavorite", b =>
                {
                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BoulderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BoulderFavorites");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderHold", b =>
                {
                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Usage")
                        .HasColumnType("integer");

                    b.HasKey("BoulderId", "HoldId");

                    b.HasIndex("HoldId");

                    b.ToTable("BoulderHolds");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderRating", b =>
                {
                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BoulderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BoulderRatings");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.GradeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedGrade")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BoulderId");

                    b.HasIndex("ProposedByUserId");

                    b.ToTable("GradeProposals");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.HangboardSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AdditionalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("EdgeSizeMm")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HangboardSessions");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Hold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlignmentSourceHoldId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnKickboard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean");

                    b.Property<int?>("Material")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("ShapePoints")
                        .HasColumnType("text");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("WallId", "Generation");

                    b.ToTable("Holds");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.PullupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AdditionalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PullupSessions");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ProgressionWindowDays")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Wall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Angle")
                        .HasColumnType("integer");

                    b.Property<string>("BorderPoints")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentGeneration")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StagedByUserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("StagedPhoto")
                        .HasColumnType("bytea");

                    b.Property<string>("StagedPhotoContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StagingMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("\"ShareToken\" IS NOT NULL");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "WallId");

                    b.HasIndex("WallId");

                    b.ToTable("WallMembers");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PreviousPhoto")
                        .HasColumnType("bytea");

                    b.Property<string>("PreviousPhotoContentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResetByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResetByUserId");

                    b.HasIndex("WallId", "Generation")
                        .IsUnique();

                    b.ToTable("WallResets");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Angle")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid");

                    b.Property<int>("Yaw")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WallId", "SortOrder");

                    b.ToTable("WallSegments");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.ActivityLogEntry", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany()
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("User");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Attempt", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("Attempts")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Boulder", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany("Boulders")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderComment", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("Comments")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderFavorite", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("Favorites")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderHold", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("BoulderHolds")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.Hold", "Hold")
                        .WithMany("BoulderHolds")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("Hold");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.BoulderRating", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("Ratings")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.GradeProposal", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Boulder", "Boulder")
                        .WithMany("GradeProposals")
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.User", "ProposedBy")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boulder");

                    b.Navigation("ProposedBy");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.HangboardSession", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany("HangboardSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Hold", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany("Holds")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.PullupSession", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany("PullupSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Wall", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallMember", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "User")
                        .WithMany("WallMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany("Members")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallReset", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.User", "ResetBy")
                        .WithMany()
                        .HasForeignKey("ResetByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany("Resets")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResetBy");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.WallSegment", b =>
                {
                    b.HasOne("Blocwerk.Core.Entities.Wall", "Wall")
                        .WithMany("Segments")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Boulder", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("BoulderHolds");

                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("GradeProposals");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Hold", b =>
                {
                    b.Navigation("BoulderHolds");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("HangboardSessions");

                    b.Navigation("PullupSessions");

                    b.Navigation("WallMemberships");
                });

            modelBuilder.Entity("Blocwerk.Core.Entities.Wall", b =>
                {
                    b.Navigation("Boulders");

                    b.Navigation("Holds");

                    b.Navigation("Members");

                    b.Navigation("Resets");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
